name: Playwright Tests
on:
  # 1. Manually trigger through GitHub UI
  workflow_dispatch:
  # 2. Run on test code changes
  push:
    paths:
      - 'tests/**'
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      API_KEY: 'M7W9BUGRIJD39FSH'
      TESTING_URL: 'https://www.alphavantage.co/query'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project='chromium'
